### ISSUE TITLE
`lungo:activate` does not exist

### ISSUE THREAD

**Issue by bukinoshita** [sindresorhus/lungo-cli#1]
I'm using node `v10.12.0` and I'm getting this error when running any `lungo` command.

```bash
Error: Command failed: open lungo:activate?
The file /Users/bukinoshita/github/lungo:activate? does not exist.

    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
```

**Comment by sindresorhus** [comment]
Do you have https://sindresorhus.com/lungo installed?

**Comment by bukinoshita** [comment]
Yup! I do

**Comment by sindresorhus** [comment]
And you have Lungo v1.5.0? If so, maybe you have to launch it once first.

**Comment by bukinoshita** [comment]
Restarted Lungo and now it's working just fine! Thanks
